keys:
  - &users:
    - &flodet age1vr2x2m3xg7hqkzzegz9w4p2gakta6xp3k5wdr0p3u9mztvvrlacswrmu78
  - &hosts:

creation_rules:
  - path_regex:  secrets.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *flodet